### ISSUE TITLE
Ненужное приведение типа str()

### ISSUE THREAD

**Issue by DanaZL** [as83davydov/lesson1#1]
https://github.com/as83davydov/lesson1/blob/130cbc8de40263f84a54bf512e37f14b5f313638/types.py#L15

.upper() может работать только со строкой и возвращать только строку, поэтому делать str() после него ненужно

**Comment by as83davydov** [comment]
Исправил

**Comment by DanaZL** [comment]
а закоммитил исправление?

**Comment by as83davydov** [comment]
Теперь да )
